dataset_id: "ADCY7_proteomics_2"
project_dir: "projects/ADCY7_proteomics_2"

input_file: "data/ADCY7_proteomics_2.xlsx"
input_sheet: "差异表达矩阵(未筛选)"

# 本批没有 sample-level abundance
sample_metadata: null

case_group: "ADCY7"
control_group: "NC"

protein_id_col: "Accession"
gene_symbol_col: "Gene Name"
description_col: "Description"
unique_peptides_col: "Unique peptides"

# 本批没有 GeneID，后续由 SYMBOL 映射 ENTREZID
gene_id_col: null

vendor_logFC_col: "log2FoldChange"
vendor_pvalue_col: "p-value"
vendor_qvalue_col: "q-value"

deg_pvalue_cutoff: 0.05
deg_qvalue_cutoff: 0.05
deg_logFC_cutoff: 0.5

volcano_qvalue_cutoff: 0.05
volcano_logFC_cutoff: 0.5
volcano_label_n: 5

# 没有 sample abundance，因此 heatmap 应自动 skip
heatmap_top_n: 30

enrichment_gene_logFC_cutoff: 0.5
enrichment_pvalue_cutoff: 0.05
enrichment_qvalue_cutoff: 0.05

min_GS_size: 10
max_GS_size: 500
show_category_n: 15

# 没有 moderated t，使用 pre-ranked score
gsea_ranking_method: "signed_log10_p"

gsea_pvalue_cutoff: 0.05
gsea_FDR_cutoff: 0.05
gsea_min_GS_size: 10
gsea_max_GS_size: 500
gsea_show_category_n: 15

gsea_draw_curves: false
gsea_curve_n: 3