pathway_set:
  - HALLMARK_TNFA_SIGNALING_VIA_NFKB
  - HALLMARK_INTERFERON_GAMMA_RESPONSE
  - HALLMARK_COMPLEMENT
  - HALLMARK_IL2_STAT5_SIGNALING
  - HALLMARK_INTERFERON_ALPHA_RESPONSE
  - HALLMARK_INFLAMMATORY_RESPONSE
  - HALLMARK_IL6_JAK_STAT3_SIGNALING