dataset_id: "LM3"
project_dir: "projects/U251_LM3_RNA-seq"
input_file: "datasets/raw/基因表达量检测结果-LM3.xlsx"
sample_metadata: "metadata/LM3_samples.tsv"
gene_id_col: "gene_id"
case_group: "OE"
control_group: "NC"
expression_cutoff: 0.5
min_samples: 3
limma_FDR_cutoff: 0.05
deg_FDR_cutoff: 0.05
deg_logFC_cutoff: 0.5
pvalue_cutoff: 0.05
TREAT_lfc_cutoff: 1
TREAT_FDR_cutoff: 0.05
downstream_deg_method: "limma_pvalue"
volcano_FDR_cutoff: 0.05
volcano_logFC_cutoff: 1
volcano_label_n: 5
heatmap_top_n: 30
enrichment_FDR_cutoff: 0.05
min_GS_size: 10
max_GS_size: 500
show_category_n: 15
